### ISSUE TITLE
assert dot_button is not None

### ISSUE THREAD

**Issue by gunar** [MatthieuBizien/roam-to-git#16]
The Github Action worked flawlessly the first time (ie when I set it up) but has been failing every hourly execution since then.

```
2020-05-05 13:08:58.683 | DEBUG    | roam_to_git.scrapping:download_rr_archive:79 - Closed browser json
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.2/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 71, in main
    scrap(markdown_zip_path, json_zip_path, config)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 253, in scrap
    asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 69, in download_rr_archive
    return await _download_rr_archive(document, output_type, output_directory, config,
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 123, in _download_rr_archive
    assert dot_button is not None
AssertionError
2020-05-05 13:08:58.732 | DEBUG    | roam_to_git.scrapping:_kill_child_process:216 - Terminate child process [psutil.Process(pid=2935, name='chrome', started='13:07:00'), psutil.Process(pid=2941, name='chrome', started='13:07:01'), psutil.Process(pid=2943, name='chrome', started='13:07:01'), psutil.Process(pid=2966, name='chrome', started='13:07:04')]
##[error]Process completed with exit code 1.
```

**Comment by lukaskawerau** [comment]
I have the same issue - worked 3 out of 10 runs, same error as OP.

**Comment by MatthieuBizien** [comment]
It is because Roam servers are very slow sometimes, so we hit the timeout. The good news is that if you use github actions or a cron, it doesn't matter if some runs fail.

**Comment by gunar** [comment]
Thanks for the answer! Is it feasible to increase the timeout?

**Comment by MatthieuBizien** [comment]
The commit above doubled the timeout ;)

**Comment by gunar** [comment]
Sorry, my bad! Thank you!!
