### ISSUE TITLE
All files were deleted during a backup

### ISSUE THREAD

**Issue by arigreen** [MatthieuBizien/roam-to-git#18]
4 hours ago there was a commit that deleted the entire contents of my DB, and 3 hours ago there's a commit that appears to restore everything.

Backup logs from the commit that deleted everything:

```
Run roam-to-git --skip-git .
2020-05-08 14:10:43.784 | DEBUG    | roam_to_git.__main__:main:53 - No secret found at /home/runner/work/roam/roam/.env
2020-05-08 14:10:43.799 | DEBUG    | roam_to_git.scrapping:download_rr_archive:54 - Creating browser
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.

  0%|          | 0/108773488 [00:00<?, ?it/s]
 18%|█▊        | 19896320/108773488 [00:00<00:00, 198908852.59it/s]
 35%|███▌      | 38307840/108773488 [00:00<00:00, 194190292.74it/s]
 54%|█████▎    | 58327040/108773488 [00:00<00:00, 195925297.80it/s]
 71%|███████▏  | 77660160/108773488 [00:00<00:00, 192858088.73it/s]
 90%|█████████ | 98324480/108773488 [00:00<00:00, 196760428.21it/s]
100%|██████████| 108773488/108773488 [00:00<00:00, 198165231.91it/s]
[W:pyppeteer.chromium_downloader] 
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: /home/runner/.local/share/pyppeteer/local-chromium/588429
2020-05-08 14:10:49.574 | DEBUG    | roam_to_git.scrapping:download_rr_archive:54 - Creating browser
2020-05-08 14:10:50.119 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:91 - Configure downloads to /tmp/tmp3cr8s8ho
2020-05-08 14:10:50.130 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:91 - Configure downloads to /tmp/tmp5fxbr42q
2020-05-08 14:10:50.153 | DEBUG    | roam_to_git.scrapping:signin:181 - Opening signin page
2020-05-08 14:10:50.165 | DEBUG    | roam_to_git.scrapping:signin:181 - Opening signin page
2020-05-08 14:10:54.844 | DEBUG    | roam_to_git.scrapping:signin:185 - Fill email '***'
2020-05-08 14:10:55.096 | DEBUG    | roam_to_git.scrapping:signin:185 - Fill email '***'
2020-05-08 14:10:56.015 | DEBUG    | roam_to_git.scrapping:signin:190 - Fill password
2020-05-08 14:10:56.283 | DEBUG    | roam_to_git.scrapping:signin:190 - Fill password
2020-05-08 14:10:56.936 | DEBUG    | roam_to_git.scrapping:signin:195 - Click on sign-in
2020-05-08 14:10:57.195 | DEBUG    | roam_to_git.scrapping:signin:195 - Click on sign-in
2020-05-08 14:10:59.164 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-05-08 14:10:59.416 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-05-08 14:11:24.210 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:128 - Launch download popup
2020-05-08 14:11:25.485 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:128 - Launch download popup
2020-05-08 14:11:26.568 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:142 - Checking download type
2020-05-08 14:11:26.591 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser json
2020-05-08 14:11:26.614 | DEBUG    | roam_to_git.scrapping:download_rr_archive:77 - Closed browser json
2020-05-08 14:11:26.614 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (2906), thread 'MainThread' (140148425639744):
Traceback (most recent call last):
> File "/opt/hostedtoolcache/Python/3.8.2/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
    └ <function load_entry_point at 0x7f76d4ee55e0>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
    scrap(markdown_zip_path, json_zip_path, config)
    │     │                  │              └ <roam_to_git.scrapping.Config object at 0x7f76d18ec0a0>
    │     │                  └ PosixPath('/tmp/tmp5fxbr42q')
    │     └ PosixPath('/tmp/tmp3cr8s8ho')
    └ <function scrap at 0x7f76d18e8a60>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 250, in scrap
    asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
    │       │                                   │       │       └ [<coroutine object download_rr_archive at 0x7f76d1c14dc0>, <coroutine object download_rr_archive at 0x7f76d1d1b140>]
    │       │                                   │       └ <function gather at 0x7f76d3860160>
    │       │                                   └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/__init__.py'>
    │       └ <built-in function get_event_loop>
    └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/__init__.py'>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
           │      └ <method 'result' of '_asyncio.Future' objects>
           └ <_GatheringFuture finished exception=AssertionError()>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 68, in download_rr_archive
    return await _download_rr_archive(document, output_type, output_directory, config)
                 │                    │         │            │                 └ <roam_to_git.scrapping.Config object at 0x7f76d18ec0a0>
                 │                    │         │            └ PosixPath('/tmp/tmp5fxbr42q')
                 │                    │         └ 'json'
                 │                    └ <pyppeteer.page.Page object at 0x7f76d12244c0>
                 └ <function _download_rr_archive at 0x7f76d18e8820>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 143, in _download_rr_archive
    button, button_text = await get_dropdown_button()
                                └ <function _download_rr_archive.<locals>.get_dropdown_button at 0x7f76d0f91670>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 136, in get_dropdown_button
    assert dropdown_button is not None
           └ None

AssertionError: assert dropdown_button is not None
2020-05-08 14:11:26.633 | DEBUG    | roam_to_git.scrapping:_kill_child_process:213 - Terminate child process [psutil.Process(pid=2925, name='chrome', started='14:10:46'), psutil.Process(pid=2931, name='chrome', started='14:10:47'), psutil.Process(pid=2952, name='chrome', started='14:10:49'), psutil.Process(pid=2963, name='chrome', started='14:10:49'), psutil.Process(pid=2933, name='chrome', started='14:10:47'), psutil.Process(pid=2951, name='chrome', started='14:10:49')]
```

**Comment by jborichevskiy** [comment]
> 4 hours ago there was a commit that deleted the entire contents of my DB

Just to be sure: I assume by DB you are referring to the git backup contents and not your actual Roam database?

Assuming that's the case, I'm seeing something similar. Different stacktrace but same behavior in deleting (clearing) all committed files. 

Seems like one potential change may be to assert `Run backup` succeeded before proceeding to `Commit changes`. Planning to poke at this further when I have time. 

```
2020-05-13T17:06:05.4475912Z 2020-05-13 17:06:05.446 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser json
2020-05-13T17:06:05.4764690Z 2020-05-13 17:06:05.475 | DEBUG    | roam_to_git.scrapping:download_rr_archive:77 - Closed browser json
2020-05-13T17:06:05.4900904Z 2020-05-13 17:06:05.478 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (40066), thread 'MainThread' (140205080614720):
2020-05-13T17:06:05.4902768Z Traceback (most recent call last):
2020-05-13T17:06:05.4905140Z > File "/opt/hostedtoolcache/Python/3.8.2/x64/bin/roam-to-git", line 11, in <module>
2020-05-13T17:06:05.4906003Z     load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
2020-05-13T17:06:05.4907948Z     └ <function load_entry_point at 0x7f8405d4a5e0>
2020-05-13T17:06:05.4910649Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
2020-05-13T17:06:05.4911722Z     scrap(markdown_zip_path, json_zip_path, config)
2020-05-13T17:06:05.4912872Z     │     │                  │              └ <roam_to_git.scrapping.Config object at 0x7f8402750220>
2020-05-13T17:06:05.4913674Z     │     │                  └ PosixPath('/tmp/tmpdhcz_sse')
2020-05-13T17:06:05.4914345Z     │     └ PosixPath('/tmp/tmpi8mgfjjb')
2020-05-13T17:06:05.4914994Z     └ <function scrap at 0x7f840274da60>
2020-05-13T17:06:05.4919454Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 250, in scrap
2020-05-13T17:06:05.4919668Z     asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
2020-05-13T17:06:05.4921069Z     │       │                                   │       │       └ [<coroutine object download_rr_archive at 0x7f8402724340>, <coroutine object download_rr_archive at 0x7f84027243c0>]
2020-05-13T17:06:05.4921912Z     │       │                                   │       └ <function gather at 0x7f84046c0160>
2020-05-13T17:06:05.4922731Z     │       │                                   └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/__init__.py'>
2020-05-13T17:06:05.4923137Z     │       └ <built-in function get_event_loop>
2020-05-13T17:06:05.4923621Z     └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/__init__.py'>
2020-05-13T17:06:05.4923896Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-05-13T17:06:05.4924076Z     return future.result()
2020-05-13T17:06:05.4924417Z            │      └ <method 'result' of '_asyncio.Future' objects>
2020-05-13T17:06:05.4924832Z            └ <_GatheringFuture finished exception=ValueError('not enough values to unpack (expected 1, got 0)')>
2020-05-13T17:06:05.4925704Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 68, in download_rr_archive
2020-05-13T17:06:05.4925910Z     return await _download_rr_archive(document, output_type, output_directory, config)
2020-05-13T17:06:05.4926355Z                  │                    │         │            │                 └ <roam_to_git.scrapping.Config object at 0x7f8402750220>
2020-05-13T17:06:05.4926724Z                  │                    │         │            └ PosixPath('/tmp/tmpdhcz_sse')
2020-05-13T17:06:05.4927052Z                  │                    │         └ 'json'
2020-05-13T17:06:05.4927413Z                  │                    └ <pyppeteer.page.Page object at 0x7f84026ee490>
2020-05-13T17:06:05.4927760Z                  └ <function _download_rr_archive at 0x7f840274d820>
2020-05-13T17:06:05.4928382Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 130, in _download_rr_archive
2020-05-13T17:06:05.4928857Z     export_all, = [b for b in divs_pb3 if await get_text(document, b) == 'export all']
2020-05-13T17:06:05.4929270Z                               │                 │        └ <pyppeteer.page.Page object at 0x7f84026ee490>
2020-05-13T17:06:05.4929650Z                               │                 └ <function get_text at 0x7f8404539e50>
2020-05-13T17:06:05.4930124Z                               └ [<pyppeteer.element_handle.ElementHandle object at 0x7f840117d5b0>, <pyppeteer.element_handle.ElementHandle object at 0x7f840...
2020-05-13T17:06:05.4930258Z 
2020-05-13T17:06:05.4930407Z ValueError: not enough values to unpack (expected 1, got 0)
2020-05-13T17:06:05.5131683Z 2020-05-13 17:06:05.511 | DEBUG    | roam_to_git.scrapping:_kill_child_process:213 - Terminate child process [psutil.Process(pid=40076, name='chrome', started='17:05:33'), psutil.Process(pid=40086, name='chrome', started='17:05:35'), psutil.Process(pid=40120, name='chrome', started='17:05:40'), psutil.Process(pid=40132, name='chrome', started='17:05:40'), psutil.Process(pid=40089, name='chrome', started='17:05:35'), psutil.Process(pid=40119, name='chrome', started='17:05:40')]
2020-05-13T17:06:05.6075992Z ##[group]Run elstudio/actions-js-build/commit@v3
```
