### ISSUE TITLE
Seeing An Assertion

### ISSUE THREAD

**Issue by aakar** [MatthieuBizien/roam-to-git#22]
I've not been able to backup at all.  Keep running into this issue via the Action.

`    2020-05-14 17:01:30.850 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:91 - Configure downloads to /tmp/tmpjneln7kw
2020-05-14 17:01:30.872 | DEBUG    | roam_to_git.scrapping:signin:181 - Opening signin page
2020-05-14 17:01:30.885 | DEBUG    | roam_to_git.scrapping:signin:181 - Opening signin page
2020-05-14 17:01:35.739 | DEBUG    | roam_to_git.scrapping:signin:185 - Fill email '***'
2020-05-14 17:01:35.835 | DEBUG    | roam_to_git.scrapping:signin:185 - Fill email '***'
2020-05-14 17:01:37.006 | DEBUG    | roam_to_git.scrapping:signin:190 - Fill password
2020-05-14 17:01:37.115 | DEBUG    | roam_to_git.scrapping:signin:190 - Fill password
2020-05-14 17:01:38.181 | DEBUG    | roam_to_git.scrapping:signin:195 - Click on sign-in
2020-05-14 17:01:38.285 | DEBUG    | roam_to_git.scrapping:signin:195 - Click on sign-in
2020-05-14 17:01:40.419 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-05-14 17:01:40.512 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-05-14 17:05:05.206 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser markdown
2020-05-14 17:05:05.206 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser json
2020-05-14 17:05:05.235 | DEBUG    | roam_to_git.scrapping:download_rr_archive:77 - Closed browser markdown
2020-05-14 17:05:05.252 | DEBUG    | roam_to_git.scrapping:download_rr_archive:77 - Closed browser json
2020-05-14 17:05:05.253 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (3394), thread 'MainThread' (139937934346048):
    Traceback (most recent call last):
> File "/opt/hostedtoolcache/Python/3.8.2/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
    └ <function load_entry_point at 0x7f45d2ac65e0>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
    scrap(markdown_zip_path, json_zip_path, config)
    │     │                  │              └ <roam_to_git.scrapping.Config object at 0x7f45cf4fd0d0>
    │     │                  └ PosixPath('/tmp/tmpjneln7kw')
    │     └ PosixPath('/tmp/tmpv0t13sqw')
    └ <function scrap at 0x7f45cf4f9a60>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 250, in scrap
    asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
    │       │                                   │       │       └ [<coroutine object download_rr_archive at 0x7f45cf825dc0>, <coroutine object download_rr_archive at 0x7f45cf92b140>]
    │       │                                   │       └ <function gather at 0x7f45d1472160>
    │       │                                   └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/__init__.py'>
    │       └ <built-in function get_event_loop>

    └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/__init__.py'>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
           │      └ <method 'result' of '_asyncio.Future' objects>
           └ <_GatheringFuture finished exception=AssertionError('All roads leads to Roam, but that one is too long. Try again when Roam s...
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 68, in download_rr_archive
    return await _download_rr_archive(document, output_type, output_directory, config)
                 │                    │         │            │                 └ <roam_to_git.scrapping.Config object at 0x7f45cf4fd0d0>
                 │                    │         │            └ PosixPath('/tmp/tmpv0t13sqw')
                 │                    │         └ 'markdown'
                 │                    └ <pyppeteer.page.Page object at 0x7f45cedbb1f0>
                 └ <function _download_rr_archive at 0x7f45cf4f9820>
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 119, in _download_rr_archive
    assert dot_button is not None, "All roads leads to Roam, but that one is too long. Try " \
           └ None

AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.`

**Comment by MatthieuBizien** [comment]
Do you still have that error? If so, could you run the script manually, with the option `--debug`?
