### ISSUE TITLE
All backups starting from ~16 hours ago are failing with NetworkError: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by Stvad** [MatthieuBizien/roam-to-git#24]
See  a multitude of WF runs here: https://github.com/Stvad/roam-notes-workflow/actions

Example log:
```
2020-05-24T20:16:16.8253367Z [W:pyppeteer.chromium_downloader] chromium extracted to: /home/runner/.local/share/pyppeteer/local-chromium/588429
2020-05-24T20:16:18.5849601Z 2020-05-24 20:16:18.584 | DEBUG    | roam_to_git.scrapping:download_rr_archive:54 - Creating browser
2020-05-24T20:16:19.1361020Z 2020-05-24 20:16:19.135 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:91 - Configure downloads to /tmp/tmpv9fg_q9r
2020-05-24T20:16:19.1477421Z 2020-05-24 20:16:19.147 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:91 - Configure downloads to /tmp/tmplzquag8l
2020-05-24T20:16:19.1712150Z 2020-05-24 20:16:19.170 | DEBUG    | roam_to_git.scrapping:signin:181 - Opening signin page
2020-05-24T20:16:19.1837365Z 2020-05-24 20:16:19.183 | DEBUG    | roam_to_git.scrapping:signin:181 - Opening signin page
2020-05-24T20:16:24.0680539Z 2020-05-24 20:16:24.067 | DEBUG    | roam_to_git.scrapping:signin:185 - Fill email '***'
2020-05-24T20:16:24.1400072Z 2020-05-24 20:16:24.139 | DEBUG    | roam_to_git.scrapping:signin:185 - Fill email '***'
2020-05-24T20:16:24.9369538Z 2020-05-24 20:16:24.936 | DEBUG    | roam_to_git.scrapping:signin:190 - Fill password
2020-05-24T20:16:25.0070283Z 2020-05-24 20:16:25.006 | DEBUG    | roam_to_git.scrapping:signin:190 - Fill password
2020-05-24T20:16:26.4999082Z 2020-05-24 20:16:26.499 | DEBUG    | roam_to_git.scrapping:signin:195 - Click on sign-in
2020-05-24T20:16:26.5701911Z 2020-05-24 20:16:26.569 | DEBUG    | roam_to_git.scrapping:signin:195 - Click on sign-in
2020-05-24T20:16:28.7279610Z 2020-05-24 20:16:28.727 | DEBUG    | roam_to_git.scrapping:go_to_database:205 - Load database from url 'https://roamresearch.com/#/app/***'
2020-05-24T20:16:28.7834035Z 2020-05-24 20:16:28.782 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-05-24T20:16:28.7986602Z 2020-05-24 20:16:28.798 | DEBUG    | roam_to_git.scrapping:go_to_database:205 - Load database from url 'https://roamresearch.com/#/app/***'
2020-05-24T20:16:28.8578568Z 2020-05-24 20:16:28.857 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-05-24T20:16:29.5277156Z 2020-05-24 20:16:29.527 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser markdown
2020-05-24T20:16:29.6028381Z 2020-05-24 20:16:29.602 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser json
2020-05-24T20:16:30.9261565Z 2020-05-24 20:16:30.925 | DEBUG    | roam_to_git.scrapping:download_rr_archive:77 - Closed browser markdown
2020-05-24T20:16:30.9356856Z 2020-05-24 20:16:30.926 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (2691), thread 'MainThread' (140435242338112):
2020-05-24T20:16:30.9357586Z Traceback (most recent call last):
2020-05-24T20:16:30.9358093Z 
2020-05-24T20:16:30.9360296Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 99, in evaluateHandle
2020-05-24T20:16:30.9361514Z     _obj = await self._client.send('Runtime.callFunctionOn', {
2020-05-24T20:16:30.9362580Z                  â”‚    â”‚       â”” <function CDPSession.send at 0x7fb999b105e0>
2020-05-24T20:16:30.9363511Z                  â”‚    â”” <pyppeteer.connection.CDPSession object at 0x7fb998ec7370>
2020-05-24T20:16:30.9364390Z                  â”” <pyppeteer.execution_context.ExecutionContext object at 0x7fb998edf9a0>
2020-05-24T20:16:30.9364854Z 
2020-05-24T20:16:30.9365356Z pyppeteer.errors.NetworkError: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id
2020-05-24T20:16:30.9365723Z 
2020-05-24T20:16:30.9366046Z 
2020-05-24T20:16:30.9366456Z During handling of the above exception, another exception occurred:
2020-05-24T20:16:30.9366766Z 
2020-05-24T20:16:30.9367075Z 
2020-05-24T20:16:30.9367473Z Traceback (most recent call last):
2020-05-24T20:16:30.9367796Z 
2020-05-24T20:16:30.9368558Z > File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/roam-to-git", line 11, in <module>
2020-05-24T20:16:30.9369415Z     load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
2020-05-24T20:16:30.9370278Z     â”” <function load_entry_point at 0x7fb99c8a15e0>
2020-05-24T20:16:30.9371337Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
2020-05-24T20:16:30.9372125Z     scrap(markdown_zip_path, json_zip_path, config)
2020-05-24T20:16:30.9372971Z     â”‚     â”‚                  â”‚              â”” <roam_to_git.scrapping.Config object at 0x7fb99922d8b0>
2020-05-24T20:16:30.9374212Z     â”‚     â”‚                  â”” PosixPath('/tmp/tmplzquag8l')
2020-05-24T20:16:30.9374991Z     â”‚     â”” PosixPath('/tmp/tmpv9fg_q9r')
2020-05-24T20:16:30.9375757Z     â”” <function scrap at 0x7fb9992344c0>
2020-05-24T20:16:30.9376722Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 250, in scrap
2020-05-24T20:16:30.9377305Z     asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
2020-05-24T20:16:30.9378223Z     â”‚       â”‚                                   â”‚       â”‚       â”” [<coroutine object download_rr_archive at 0x7fb99923e540>, <coroutine object download_rr_archive at 0x7fb99923e140>]
2020-05-24T20:16:30.9380260Z     â”‚       â”‚                                   â”‚       â”” <function gather at 0x7fb99b223310>
2020-05-24T20:16:30.9382183Z     â”‚       â”‚                                   â”” <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/__init__.py'>
2020-05-24T20:16:30.9384002Z     â”‚       â”” <built-in function get_event_loop>
2020-05-24T20:16:30.9385838Z     â”” <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/__init__.py'>
2020-05-24T20:16:30.9387481Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-05-24T20:16:30.9388921Z     return future.result()
2020-05-24T20:16:30.9391000Z            â”‚      â”” <method 'result' of '_asyncio.Future' objects>
2020-05-24T20:16:30.9393194Z            â”” <_GatheringFuture finished exception=NetworkError('Execution context was destroyed, most likely because of a navigation.')>
2020-05-24T20:16:30.9395283Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 68, in download_rr_archive
2020-05-24T20:16:30.9396865Z     return await _download_rr_archive(document, output_type, output_directory, config)
2020-05-24T20:16:30.9398755Z                  â”‚                    â”‚         â”‚            â”‚                 â”” <roam_to_git.scrapping.Config object at 0x7fb99922d8b0>
2020-05-24T20:16:30.9403948Z                  â”‚                    â”‚         â”‚            â”” PosixPath('/tmp/tmpv9fg_q9r')
2020-05-24T20:16:30.9404986Z                  â”‚                    â”‚         â”” 'markdown'
2020-05-24T20:16:30.9405688Z                  â”‚                    â”” <pyppeteer.page.Page object at 0x7fb998ec7550>
2020-05-24T20:16:30.9406348Z                  â”” <function _download_rr_archive at 0x7fb999234280>
2020-05-24T20:16:30.9407222Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 105, in _download_rr_archive
2020-05-24T20:16:30.9407974Z     dot_button = await document.querySelector(".bp3-icon-more")
2020-05-24T20:16:30.9408686Z                        â”‚        â”” <function Page.querySelector at 0x7fb999298f70>
2020-05-24T20:16:30.9409376Z                        â”” <pyppeteer.page.Page object at 0x7fb998ec7550>
2020-05-24T20:16:30.9410181Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/page.py", line 371, in querySelector
2020-05-24T20:16:30.9410601Z     return await frame.querySelector(selector)
2020-05-24T20:16:30.9411214Z                  â”‚     â”‚             â”” '.bp3-icon-more'
2020-05-24T20:16:30.9411861Z                  â”‚     â”” <function Frame.querySelector at 0x7fb999261c10>
2020-05-24T20:16:30.9412764Z                  â”” <pyppeteer.frame_manager.Frame object at 0x7fb998efc400>
2020-05-24T20:16:30.9413589Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 317, in querySelector
2020-05-24T20:16:30.9414058Z     value = await document.querySelector(selector)
2020-05-24T20:16:30.9414661Z                   â”‚        â”‚             â”” '.bp3-icon-more'
2020-05-24T20:16:30.9415316Z                   â”‚        â”” <function ElementHandle.querySelector at 0x7fb9995db550>
2020-05-24T20:16:30.9416005Z                   â”” <pyppeteer.element_handle.ElementHandle object at 0x7fb998edf7c0>
2020-05-24T20:16:30.9417123Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/element_handle.py", line 358, in querySelector
2020-05-24T20:16:30.9417560Z     handle = await self.executionContext.evaluateHandle(
2020-05-24T20:16:30.9418161Z                    â”‚    â”” <property object at 0x7fb999699bd0>
2020-05-24T20:16:30.9418859Z                    â”” <pyppeteer.element_handle.ElementHandle object at 0x7fb998edf7c0>
2020-05-24T20:16:30.9419631Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 108, in evaluateHandle
2020-05-24T20:16:30.9420053Z     _rewriteError(e)
2020-05-24T20:16:30.9420644Z     â”” <function _rewriteError at 0x7fb99969a0d0>
2020-05-24T20:16:30.9421411Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 237, in _rewriteError
2020-05-24T20:16:30.9421844Z     raise type(error)(msg)
2020-05-24T20:16:30.9422490Z                â”‚      â”” 'Execution context was destroyed, most likely because of a navigation.'
2020-05-24T20:16:30.9423226Z                â”” NetworkError('Protocol error (Runtime.callFunctionOn): Cannot find context with specified id')
2020-05-24T20:16:30.9423508Z 
2020-05-24T20:16:30.9423858Z pyppeteer.errors.NetworkError: Execution context was destroyed, most likely because of a navigation.
2020-05-24T20:16:30.9424200Z Traceback (most recent call last):
2020-05-24T20:16:30.9424913Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 99, in evaluateHandle
2020-05-24T20:16:30.9425772Z     _obj = await self._client.send('Runtime.callFunctionOn', {
2020-05-24T20:16:30.9426253Z pyppeteer.errors.NetworkError: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id
2020-05-24T20:16:30.9426514Z 
2020-05-24T20:16:30.9426804Z During handling of the above exception, another exception occurred:
2020-05-24T20:16:30.9427060Z 
2020-05-24T20:16:30.9427359Z Traceback (most recent call last):
2020-05-24T20:16:30.9428091Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/roam-to-git", line 11, in <module>
2020-05-24T20:16:30.9428776Z     load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
2020-05-24T20:16:30.9429593Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/loguru/_logger.py", line 1210, in catch_wrapper
2020-05-24T20:16:30.9430289Z     return function(*args, **kwargs)
2020-05-24T20:16:30.9432358Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
2020-05-24T20:16:30.9432617Z     scrap(markdown_zip_path, json_zip_path, config)
2020-05-24T20:16:30.9433178Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 250, in scrap
2020-05-24T20:16:30.9433417Z     asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
2020-05-24T20:16:30.9433705Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-05-24T20:16:30.9433923Z     return future.result()
2020-05-24T20:16:30.9434487Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 68, in download_rr_archive
2020-05-24T20:16:30.9434751Z     return await _download_rr_archive(document, output_type, output_directory, config)
2020-05-24T20:16:30.9435308Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 105, in _download_rr_archive
2020-05-24T20:16:30.9435763Z     dot_button = await document.querySelector(".bp3-icon-more")
2020-05-24T20:16:30.9436289Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/page.py", line 371, in querySelector
2020-05-24T20:16:30.9436523Z     return await frame.querySelector(selector)
2020-05-24T20:16:30.9437051Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 317, in querySelector
2020-05-24T20:16:30.9437521Z     value = await document.querySelector(selector)
2020-05-24T20:16:30.9438109Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/element_handle.py", line 358, in querySelector
2020-05-24T20:16:30.9438342Z     handle = await self.executionContext.evaluateHandle(
2020-05-24T20:16:30.9438896Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 108, in evaluateHandle
2020-05-24T20:16:30.9439111Z     _rewriteError(e)
2020-05-24T20:16:30.9439636Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 237, in _rewriteError
2020-05-24T20:16:30.9439875Z     raise type(error)(msg)
2020-05-24T20:16:30.9440107Z pyppeteer.errors.NetworkError: Execution context was destroyed, most likely because of a navigation.
2020-05-24T20:16:30.9440690Z 2020-05-24 20:16:30.942 | DEBUG    | roam_to_git.scrapping:_kill_child_process:213 - Terminate child process [psutil.Process(pid=2734, name='chrome', started='20:16:17')]
2020-05-24T20:16:30.9902387Z ##[error]Process completed with exit code 1.
```

**Comment by wshuyi** [comment]
Same here.

**Comment by MatthieuBizien** [comment]
I was able to reproduce it and to make a quick fix. 

I was wondering, for investigating the scrapping workflow, do you have multiple databases in Roam?

**Comment by Stvad** [comment]
That fixed it! Yep, I have multiple databases

**Comment by wshuyi** [comment]
Me too. Thanks!
