### ISSUE TITLE
Backup via Action failing since paywall went up

### ISSUE THREAD

**Issue by MarcusWohlsen** [MatthieuBizien/roam-to-git#25]
Running roam-to-git backup via Actions. Since the paywall has gone up, the backup fails while waiting for the interface to load. Assume it's because the login flow has changed.

2020-06-10T17:02:57.2539326Z 2020-06-10 17:02:57.253 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-06-10T17:02:57.4390657Z 2020-06-10 17:02:57.438 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:101 - Wait for interface to load
2020-06-10T17:09:42.3139891Z 2020-06-10 17:09:42.313 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser markdown
2020-06-10T17:09:42.3146177Z 2020-06-10 17:09:42.314 | DEBUG    | roam_to_git.scrapping:download_rr_archive:75 - Closing browser json
2020-06-10T17:09:42.3441770Z 2020-06-10 17:09:42.343 | DEBUG    | roam_to_git.scrapping:download_rr_archive:77 - Closed browser markdown
2020-06-10T17:09:42.3722804Z 2020-06-10 17:09:42.371 | DEBUG    | roam_to_git.scrapping:download_rr_archive:77 - Closed browser json
2020-06-10T17:09:42.3786501Z 2020-06-10 17:09:42.372 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (3978), thread 'MainThread' (139625180018496):
2020-06-10T17:09:42.3787119Z Traceback (most recent call last):
2020-06-10T17:09:42.3787532Z 
2020-06-10T17:09:42.3788453Z > File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/roam-to-git", line 11, in <module>
2020-06-10T17:09:42.3788866Z     load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
2020-06-10T17:09:42.3789345Z     └ <function load_entry_point at 0x7efd011015e0>
2020-06-10T17:09:42.3790877Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
2020-06-10T17:09:42.3791187Z     scrap(markdown_zip_path, json_zip_path, config)
2020-06-10T17:09:42.3791633Z     │     │                  │              └ <roam_to_git.scrapping.Config object at 0x7efcfda8d820>
2020-06-10T17:09:42.3792002Z     │     │                  └ PosixPath('/tmp/tmpuwmqnsjb')
2020-06-10T17:09:42.3792335Z     │     └ PosixPath('/tmp/tmpf1f99acm')
2020-06-10T17:09:42.3792661Z     └ <function scrap at 0x7efcfda954c0>
2020-06-10T17:09:42.3793172Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 251, in scrap
2020-06-10T17:09:42.3793399Z     asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
2020-06-10T17:09:42.3793922Z     │       │                                   │       │       └ [<coroutine object download_rr_archive at 0x7efcfde7de40>, <coroutine object download_rr_archive at 0x7efcfe317dc0>]
2020-06-10T17:09:42.3794344Z     │       │                                   │       └ <function gather at 0x7efcffa7f310>
2020-06-10T17:09:42.3794883Z     │       │                                   └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/__init__.py'>
2020-06-10T17:09:42.3795237Z     │       └ <built-in function get_event_loop>
2020-06-10T17:09:42.3795641Z     └ <module 'asyncio' from '/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/__init__.py'>
2020-06-10T17:09:42.3795924Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-06-10T17:09:42.3796123Z     return future.result()
2020-06-10T17:09:42.3796491Z            │      └ <method 'result' of '_asyncio.Future' objects>
2020-06-10T17:09:42.3796954Z            └ <_GatheringFuture finished exception=AssertionError('All roads leads to Roam, but that one is too long. Try again when Roam s...
2020-06-10T17:09:42.3797787Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 68, in download_rr_archive
2020-06-10T17:09:42.3798020Z     return await _download_rr_archive(document, output_type, output_directory, config)
2020-06-10T17:09:42.3798483Z                  │                    │         │            │                 └ <roam_to_git.scrapping.Config object at 0x7efcfda8d820>
2020-06-10T17:09:42.3798906Z                  │                    │         │            └ PosixPath('/tmp/tmpf1f99acm')
2020-06-10T17:09:42.3799273Z                  │                    │         └ 'markdown'
2020-06-10T17:09:42.3799662Z                  │                    └ <pyppeteer.page.Page object at 0x7efcfd3867f0>
2020-06-10T17:09:42.3800034Z                  └ <function _download_rr_archive at 0x7efcfda95280>
2020-06-10T17:09:42.3800537Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 120, in _download_rr_archive
2020-06-10T17:09:42.3800876Z     assert dot_button is not None, "All roads leads to Roam, but that one is too long. Try " \
2020-06-10T17:09:42.3801212Z            └ None
2020-06-10T17:09:42.3801314Z 
2020-06-10T17:09:42.3801498Z AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.
2020-06-10T17:09:42.3803728Z Traceback (most recent call last):
2020-06-10T17:09:42.3804481Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/roam-to-git", line 11, in <module>
2020-06-10T17:09:42.3804919Z     load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
2020-06-10T17:09:42.3805567Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/loguru/_logger.py", line 1210, in catch_wrapper
2020-06-10T17:09:42.3805784Z     return function(*args, **kwargs)
2020-06-10T17:09:42.3806249Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 76, in main
2020-06-10T17:09:42.3806503Z     scrap(markdown_zip_path, json_zip_path, config)
2020-06-10T17:09:42.3807079Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 251, in scrap
2020-06-10T17:09:42.3807296Z     asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
2020-06-10T17:09:42.3807548Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-06-10T17:09:42.3807764Z     return future.result()
2020-06-10T17:09:42.3808266Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 68, in download_rr_archive
2020-06-10T17:09:42.3808499Z     return await _download_rr_archive(document, output_type, output_directory, config)
2020-06-10T17:09:42.3809012Z   File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 120, in _download_rr_archive
2020-06-10T17:09:42.3809259Z     assert dot_button is not None, "All roads leads to Roam, but that one is too long. Try " \
2020-06-10T17:09:42.3809472Z AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.
2020-06-10T17:09:42.4315148Z ##[error]Process completed with exit code 1.
2020-06-10T17:09:42.4370242Z Post job cleanup.

**Comment by awinecki** [comment]
> FYI, you can work around this by explicitly specifying a `--database` name. It changes the way the scraper works after login to just explicitly load your database URL, which still works fine even with the current subscription notice.

You can also use `ROAMRESEARCH_DATABASE` env var for this.

By default, if you copied the workflow `main.yml` file from the repo guide, you should have env vars set up like:

![nj-screenshot 2020-06-11 at 15 01 24@2x](https://user-images.githubusercontent.com/656694/84388185-731ef500-abf4-11ea-83e8-fea2895dbb30.png)

Then you just need to add a secret to your backup repo with your graph / database name; you can find it here:

![nj-screenshot 2020-06-11 at 15 02 08@2x](https://user-images.githubusercontent.com/656694/84388282-98136800-abf4-11ea-84c1-85ffc59b30b0.png)

🙌

**Comment by MarcusWohlsen** [comment]
Yes, thanks, @awinecki, that's the trick! I'm a bit of a Github noob. Should I mark this issue closed?

**Comment by MatthieuBizien** [comment]
Hi! I can't test the use-case "one database", because I have multiple databases. I made the definition of the database mandatory, because it seems to fix that bug. Thanks @jrk and @awinecki for the solution :)
