### ISSUE TITLE
getting assertion error on self.user

### ISSUE THREAD

**Issue by rohanraval** [MatthieuBizien/roam-to-git#26]
Can't seem to debug this error. Any help would be appreciated! Thanks for this amazing tool.

- First time using roam-to-git, running on macOS. 
- I just set up the Github action exactly as specified, and this is the first time it is running the action.
- Setting the env variables using Github secrets. 

Output from the Github Actions UI when it runs:
```Run roam-to-git --skip-git .
  roam-to-git --skip-git .
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
    ROAMRESEARCH_USER: 
    ROAMRESEARCH_PASSWORD: 
    ROAMRESEARCH_DATABASE: 
2020-06-12 03:40:20.028 | DEBUG    | roam_to_git.__main__:main:53 - No secret found at /home/runner/work/roam-notes/roam-notes/.env
2020-06-12 03:40:20.028 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (3049), thread 'MainThread' (140371337385792):
Traceback (most recent call last):

> File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
    └ <function load_entry_point at 0x7faabb81f5e0>
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 58, in main
    config = Config(args.database, debug=args.debug, sleep_duration=float(args.sleep_duration))
             │      │    │               │    │                           │    └ 2.0
             │      │    │               │    │                           └ Namespace(database=None, debug=False, directory='.', skip_fetch=False, skip_git=True, skip_push=False, sleep_duration=2.0)
             │      │    │               │    └ False
             │      │    │               └ Namespace(database=None, debug=False, directory='.', skip_fetch=False, skip_git=True, skip_push=False, sleep_duration=2.0)
             │      │    └ None
             │      └ Namespace(database=None, debug=False, directory='.', skip_fetch=False, skip_git=True, skip_push=False, sleep_duration=2.0)
             └ <class 'roam_to_git.scrapping.Config'>
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 39, in __init__
    assert self.user
           │    └ ''
           └ <roam_to_git.scrapping.Config object at 0x7faab81aa8b0>

AssertionError: assert self.user
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.3/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/loguru/_logger.py", line 1210, in catch_wrapper
    return function(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 58, in main
    config = Config(args.database, debug=args.debug, sleep_duration=float(args.sleep_duration))
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 39, in __init__
    assert self.user
AssertionError
##[error]Process completed with exit code 1.
```

**Comment by MatthieuBizien** [comment]
User setup is really simple, it's just `os.environ["ROAMRESEARCH_USER"]`, so it looks like your environment variable ROAMRESEARCH_USER is empty. It should be configured with Github secrets, could you check that it is defined?

**Comment by rohanraval** [comment]
hey @MatthieuBizien thanks for replying! I checked my github secrets — I've defined a secret named "Roam" that looks like:
```
ROAMRESEARCH_USER="abcd"
ROAMRESEARCH_PASSWORD="abcd"
ROAMRESEARCH_DATABASE="abcd"
```
is this not the expected format? or do I have to somehow specify which secret to use (it seems like you can create many, although I am not doing that)

**Comment by justinpinkney** [comment]
You have to define 3 secrets. Set the first secret name to ROAMRESEARCH_USER and the value to your username etc. Each secret will correspond to one of the environment variables.

**Comment by rohanraval** [comment]
ahh my bad, stupid mistake. works now. Thanks @justinpinkney !!
