### ISSUE TITLE
Seeing `CERTIFICATE_VERIFY_FAILED` on first run

### ISSUE THREAD

**Issue by beaugunderson** [MatthieuBizien/roam-to-git#35]
**Describe the bug**

Seeing `CERTIFICATE_VERIFY_FAILED` on first run.

**To Reproduce**

- run `roam-to-git`

**Expected behavior**

- `roam-to-git` completes successfully

**Traceback**

```
2020-07-21 10:46:41.161 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (5334), thread 'MainThread' (4312686016):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fc8e8419040>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fc90833e130>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fc9083577f0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fc8e8419550>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fc90833e130>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fc8e8405e50>
    └ <urllib3.connection.HTTPSConnection object at 0x7fc9083577f0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connection.py", line 361, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fc8d8128280>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fc9083577f0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
           │       │           │                     └ 'storage.googleapis.com'
           │       │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6>
           │       └ <function SSLContext.wrap_socket at 0x7fc8f818b5e0>
           └ <ssl.SSLContext object at 0x7fc90834b3c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fc8f818c610>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fc90834b3c0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fc8f81924c0>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0>

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
```

**Run `roam-to-git --debug notes/` and report what you get.**

- N/A, Chrome has not been downloaded yet

**Please complete the following information:**
- OS: latest macOS
- Do you use Github Action? no
- Do you use multiple Roam databases? no
- Does roam-to-git use to work for you? When precisely did it stopped to work? no
- Does some backup runs are still working? no

**Comment by beaugunderson** [comment]
`PYTHONHTTPSVERIFY=0 roam-to-git` also does not work.

**Comment by beaugunderson** [comment]
I had installed roam-to-git using the python.org Python; I switched to using python3.8 as provided by `brew` instead and I no longer see a certificate error.
