### ISSUE TITLE
Unzip fails

### ISSUE THREAD

**Issue by ituri** [MatthieuBizien/roam-to-git#36]
**Describe the bug**
roam-to-git fails when run with GitHub actions.

**To Reproduce**
Start the backup.

**Expected behavior**
Run the backup.

**Traceback**
```
Run roam-to-git --skip-git .
2020-07-31 15:27:48.613 | DEBUG    | roam_to_git.__main__:main:53 - No secret found at /home/runner/work/notes/notes/.env
2020-07-31 15:27:48.615 | DEBUG    | roam_to_git.scrapping:download_rr_archive:55 - Creating browser
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
  0%|          | 0/108773488 [00:00<?, ?it/s]
  6%|▌         | 6686720/108773488 [00:00<00:01, 66762209.15it/s]
 19%|█▉        | 21186560/108773488 [00:00<00:01, 79635894.98it/s]
 34%|███▍      | 36884480/108773488 [00:00<00:00, 93369311.19it/s]
 48%|████▊     | 52295680/108773488 [00:00<00:00, 105887183.63it/s]
 62%|██████▏   | 67112960/108773488 [00:00<00:00, 103089937.41it/s]
75%|███████▍  | 81397760/108773488 [00:00<00:00, 112412818.82it/s]
 88%|████████▊ | 95375360/108773488 [00:00<00:00, 119398460.96it/s]
100%|██████████| 108773488/108773488 [00:00<00:00, 127783948.48it/s]
[W:pyppeteer.chromium_downloader] 
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: /home/runner/.local/share/pyppeteer/local-chromium/588429
2020-07-31 15:27:54.933 | DEBUG    | roam_to_git.scrapping:download_rr_archive:55 - Creating browser
2020-07-31 15:27:55.461 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:92 - Configure downloads to /tmp/tmpcdjcmlv6
2020-07-31 15:27:55.473 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:92 - Configure downloads to /tmp/tmplhhksw1h
2020-07-31 15:27:55.496 | DEBUG    | roam_to_git.scrapping:signin:183 - Opening signin page
2020-07-31 15:27:55.508 | DEBUG    | roam_to_git.scrapping:signin:183 - Opening signin page
2020-07-31 15:28:00.998 | DEBUG    | roam_to_git.scrapping:signin:187 - Fill email '***'
2020-07-31 15:28:01.051 | DEBUG    | roam_to_git.scrapping:signin:187 - Fill email '***'
2020-07-31 15:28:04.091 | DEBUG    | roam_to_git.scrapping:signin:192 - Fill password
2020-07-31 15:28:04.285 | DEBUG    | roam_to_git.scrapping:signin:192 - Fill password
2020-07-31 15:28:04.714 | DEBUG    | roam_to_git.scrapping:signin:197 - Click on sign-in
2020-07-31 15:28:04.914 | DEBUG    | roam_to_git.scrapping:signin:197 - Click on sign-in
2020-07-31 15:28:06.952 | DEBUG    | roam_to_git.scrapping:go_to_database:207 - Load database from url 'https://roamresearch.com/#/app/***'
2020-07-31 15:28:07.143 | DEBUG    | roam_to_git.scrapping:go_to_database:207 - Load database from url 'https://roamresearch.com/#/app/***'
2020-07-31 15:28:07.884 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:102 - Wait for interface to load
2020-07-31 15:28:07.990 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:102 - Wait for interface to load
2020-07-31 15:28:10.113 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:130 - Launch download popup
2020-07-31 15:28:10.202 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:130 - Launch download popup
2020-07-31 15:28:12.457 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:144 - Checking download type
2020-07-31 15:28:12.457 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:144 - Checking download type
2020-07-31 15:28:12.501 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:159 - Downloading output of type markdown
2020-07-31 15:28:12.538 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:144 - Checking download type
2020-07-31 15:28:12.583 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:148 - Changing output type to json
2020-07-31 15:28:12.809 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:164 - Wait download of markdown to /tmp/tmpcdjcmlv6
2020-07-31 15:28:13.812 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:174 - File /tmp/tmpcdjcmlv6/Roam-Export-1596209293568.zip found for markdown
2020-07-31 15:28:14.813 | DEBUG    | roam_to_git.scrapping:download_rr_archive:76 - Closing browser markdown
2020-07-31 15:28:15.129 | DEBUG    | roam_to_git.scrapping:download_rr_archive:78 - Closed browser markdown
2020-07-31 15:28:17.220 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:159 - Downloading output of type json
2020-07-31 15:28:17.524 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:164 - Wait download of json to /tmp/tmplhhksw1h
2020-07-31 15:28:18.528 | DEBUG    | roam_to_git.scrapping:_download_rr_archive:174 - File /tmp/tmplhhksw1h/Roam-Export-1596209297749.zip found for json
2020-07-31 15:28:19.530 | DEBUG    | roam_to_git.scrapping:download_rr_archive:76 - Closing browser json
2020-07-31 15:28:19.562 | DEBUG    | roam_to_git.scrapping:download_rr_archive:78 - Closed browser json
2020-07-31 15:28:19.562 | DEBUG    | roam_to_git.scrapping:scrap:253 - Scrapping finished
2020-07-31 15:28:19.564 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (3172), thread 'MainThread' (140397351790400):
Traceback (most recent call last):
> File "/opt/hostedtoolcache/Python/3.8.5/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
    └ <function load_entry_point at 0x7fb0ca124f70>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 81, in main
    raws = unzip_markdown_archive(markdown_zip_path)
           │                      └ PosixPath('/tmp/tmpcdjcmlv6')
           └ <function unzip_markdown_archive at 0x7fb0c8969310>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/fs.py", line 43, in unzip_markdown_archive
    contents = {file.filename: zip_file.read(file.filename).decode()
                               │        └ <function ZipFile.read at 0x7fb0cbfbe790>
                               └ <zipfile.ZipFile [closed]>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/fs.py", line 45, in <dictcomp>
    if not file.is_dir()}
           │    └ <function ZipInfo.is_dir at 0x7fb0cbfb98b0>
           └ <unprintable ZipInfo object>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/zipfile.py", line 551, in is_dir
    return self.filename[-1] == '/'
           │    └ <member 'filename' of 'ZipInfo' objects>
           └ <unprintable ZipInfo object>

IndexError: string index out of range
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/loguru/_logger.py", line 1149, in catch_wrapper
    return function(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 81, in main
    raws = unzip_markdown_archive(markdown_zip_path)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/fs.py", line 43, in unzip_markdown_archive
    contents = {file.filename: zip_file.read(file.filename).decode()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/fs.py", line 45, in <dictcomp>
    if not file.is_dir()}
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/zipfile.py", line 551, in is_dir
    return self.filename[-1] == '/'
IndexError: string index out of range
##[error]Process completed with exit code 1.
 Commit changes0s
  Post Run actions/checkout@v20s
  Complete job
```

**Please complete the following information:**
- Do you use Github Action? Yes.
- Do you use multiple Roam databases? No. 
- Does roam-to-git use to work for you? When precisely did it stopped to work? No, first setup.
- Does some backup runs are still working? No.

**Comment by ituri** [comment]
Any clues on this? I have set up the GitHub action more than three times now, each time double-checking my credentials. I've even reset my Roam password but none of these steps have helped so far. I still keep seeing the same error over and over again.

**Comment by ituri** [comment]
I do have Emojis in some of my page's names. Could that pose a problem?

**Comment by MatthieuBizien** [comment]
Usually not, but it may. The code above should give us an answer.

**Comment by ituri** [comment]
Where exactly would I put the code above? In a separate Python file? If yes, how do I run the program then? 

I'm sorry, but I'm not really a coder myself so I'm a bit lost here.
