### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/pdf hack.md'

### ISSUE THREAD

**Issue by ccpalmer** [MatthieuBizien/roam-to-git#40]
**Describe the bug**
first run of roam=to=git failed with: 
```
2020-08-11 16:59:03.797 | ERROR    | __main__:<module>:8 - An error has been caught in function '<module>', process 'MainProcess' (53930), thread 'MainThread' (4442066368):
Traceback (most recent call last):
> File "/Users/ccp/.local/bin/roam-to-git", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x104440700>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/Users/ccp/.local/pipx/venvs/roam-to-git/lib/python3.8/site-packages/roam_to_git/__main__.py", line 82, in main
    save_markdowns(git_path / "markdown", raws)
    │              │                      └ {'February 9th, 2020.md': '- [[Areas]] \n- \n', 'Areas.md': '- [[Dartmouth]]\n- [[Home]]\n- \n', 'Dartmouth.md': '- [[Teachin...
    │              └ PosixPath('/Users/ccp/Development/notes')
    └ <function save_markdowns at 0x103fdbaf0>
  File "/Users/ccp/.local/pipx/venvs/roam-to-git/lib/python3.8/site-packages/roam_to_git/fs.py", line 57, in save_markdowns
    with dest.open("w", encoding="utf-8") as f:
         │    │                              └ <_io.TextIOWrapper name='/Users/ccp/Development/notes/markdown/V: Note-taking While Reading.md' mode='w' encoding='utf-8'>
         │    └ <function Path.open at 0x103628e50>
         └ PosixPath('/pdf hack.md')
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
           │  │    │     │     │          │         │       └ None
           │  │    │     │     │          │         └ None
           │  │    │     │     │          └ 'utf-8'
           │  │    │     │     └ -1
           │  │    │     └ 'w'
           │  │    └ PosixPath('/pdf hack.md')
           │  └ <built-in function open>
           └ <module 'io' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/io.py'>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
           │    │              │     │      └ 438
           │    │              │     └ 16778753
           │    │              └ PosixPath('/pdf hack.md')
           │    └ <member '_accessor' of 'Path' objects>
           └ PosixPath('/pdf hack.md')
```

**To Reproduce**

**Traceback**
Please use http://gist.github.com/ or similar, and report the last line here.

**Run `roam-to-git --debug notes/` and report what you get.**
It should open a Chrome front-end, an do the scrapping. The repository content will not be modified. If applicable, add screenshots to help explain your problem.

**Please complete the following information:**
- OS: MAC OS Catalina
- Do you use Github Action? Tried
- Do you use multiple Roam databases? no
- Does roam-to-git use to work for you? When precisely did it stopped to work? first time
- Does some backup runs are still working? don't think so

**Additional context**

**Comment by quanhua92** [comment]
@ccpalmer I've found the solution to this problem. The problem here is that your page has a name "/pdf hack". When this tool tries to make a file name "/pdf hack.md", it will try to make that file in the root folder of the Linux instead of "markdown/pdf hack.md".
The simple solution is to rename your page into pdf hack without the / -> "pdf hack".

**Comment by MatthieuBizien** [comment]
It should work now without problem.
