### ISSUE TITLE
Assertion error "assert self.user"

### ISSUE THREAD

**Issue by IanQS** [MatthieuBizien/roam-to-git#41]
**Describe the bug**
Seems like the user information isn't being extracted from the secrets?  I'm DEFINITELY setting the credentials correctly as per #41 

**To Reproduce**
I don't know how to reproduce it since it doesn't seem like anyone else is having the issue

**Expected behavior**
Not running into the error

**Traceback**

```
Run roam-to-git --skip-git .
  roam-to-git --skip-git .
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.5/x64
    ROAMRESEARCH_USER: 
    ROAMRESEARCH_PASSWORD: 
    ROAMRESEARCH_DATABASE: 
2020-08-11 22:07:08.984 | DEBUG    | roam_to_git.__main__:main:53 - No secret found at /home/runner/work/Roam-Research-Backup/Roam-Research-Backup/.env
2020-08-11 22:07:08.984 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (3027), thread 'MainThread' (139709369939776):
Traceback (most recent call last):
> File "/opt/hostedtoolcache/Python/3.8.5/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
    └ <function load_entry_point at 0x7f109b2b7f70>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 58, in main
    config = Config(args.database, debug=args.debug, sleep_duration=float(args.sleep_duration))
             │      │    │               │    │                           │    └ 2.0
             │      │    │               │    │                           └ Namespace(database=None, debug=False, directory='.', skip_fetch=False, skip_git=True, skip_push=False, sleep_duration=2.0)
             │      │    │               │    └ False
             │      │    │               └ Namespace(database=None, debug=False, directory='.', skip_fetch=False, skip_git=True, skip_push=False, sleep_duration=2.0)
             │      │    └ None
             │      └ Namespace(database=None, debug=False, directory='.', skip_fetch=False, skip_git=True, skip_push=False, sleep_duration=2.0)
             └ <class 'roam_to_git.scrapping.Config'>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 39, in __init__
    assert self.user
           │    └ ''
           └ <roam_to_git.scrapping.Config object at 0x7f1097c8b490>
```

**Run `roam-to-git --debug notes/` and report what you get.**
It should open a Chrome front-end, an do the scrapping. The repository content will not be modified. If applicable, add screenshots to help explain your problem.

**Please complete the following information:**
- OS: [e.g. MacOs, Linux] Linux
- Do you use Github Action? Yes
- Do you use multiple Roam databases? No
- Does roam-to-git use to work for you? When precisely did it stopped to work?
- Does some backup runs are still working? Nope :( 

**Additional context**

**Comment by MatthieuBizien** [comment]
Hi @IanQS! Did you solve your problem? What was the fix?

**Comment by IanQS** [comment]
Apologies, I should have linked the fix too :) 

#42 fixed the issue
