### ISSUE TITLE
Backup fails with "Permission denied: '/r'"

### ISSUE THREAD

**Issue by anchpop** [MatthieuBizien/roam-to-git#55]
**Describe the bug**
Backup fails with this error:

```
2020-09-24 17:10:18.090 | DEBUG    | roam_to_git.scrapping:download_rr_archive:76 - Closing browser markdown
2020-09-24 17:10:18.126 | DEBUG    | roam_to_git.scrapping:download_rr_archive:78 - Closed browser markdown
2020-09-24 17:10:18.171 | DEBUG    | roam_to_git.scrapping:download_rr_archive:76 - Closing browser json
2020-09-24 17:10:18.215 | DEBUG    | roam_to_git.scrapping:download_rr_archive:78 - Closed browser json
2020-09-24 17:10:18.215 | DEBUG    | roam_to_git.scrapping:scrap:253 - Scrapping finished
2020-09-24 17:10:18.231 | DEBUG    | roam_to_git.fs:save_markdowns:50 - Saving markdown to /home/runner/work/notes/notes/markdown
2020-09-24 17:10:18.257 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (3168), thread 'MainThread' (140306047739712):
Traceback (most recent call last):
> File "/opt/hostedtoolcache/Python/3.8.5/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
    └ <function load_entry_point at 0x7f9b87ed0f70>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 82, in main
    save_markdowns(git_path / "markdown", raws)
    │              │                      └ {'general advice.md': '- [[applause lights]]\n    - If you can invert a piece of advice and it still makes sense, it might be...
    │              └ PosixPath('/home/runner/work/notes/notes')
    └ <function save_markdowns at 0x7f9b8679a160>
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/fs.py", line 54, in save_markdowns
    dest.parent.mkdir(parents=True, exist_ok=True)  # Needed if a new directory is used
    │    └ <property object at 0x7f9b87b69680>
    └ PosixPath('/r/drama.md')
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
    │    │               │     └ 511
    │    │               └ PosixPath('/r')
    │    └ <member '_accessor' of 'Path' objects>
    └ PosixPath('/r')

PermissionError: [Errno 13] Permission denied: '/r'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/bin/roam-to-git", line 11, in <module>
    load_entry_point('roam-to-git==0.1', 'console_scripts', 'roam-to-git')()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/loguru/_logger.py", line 1149, in catch_wrapper
    return function(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 82, in main
    save_markdowns(git_path / "markdown", raws)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/roam_to_git/fs.py", line 54, in save_markdowns
    dest.parent.mkdir(parents=True, exist_ok=True)  # Needed if a new directory is used
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/pathlib.py", line 1284, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/r'
Error: Process completed with exit code 1.
````

I'm using Github Actions and only have one database. This is my first attempt at using it. Any help would be much appreciated!

**Comment by MatthieuBizien** [comment]
I think that issue is due to a note name with special characters. It should be fixed by #93
