### ISSUE TITLE
Road to Roam too long

### ISSUE THREAD

**Issue by fernfialho** [MatthieuBizien/roam-to-git#65]
**Describe the bug**
tried to manually backup and received the error below - no backup files created

**To Reproduce**

**Expected behavior**
backup files to show up

**Traceback**
Please use http://gist.github.com/ or similar, and report the last line here.

Note: created alias for my user name throughout

2020-10-30 11:55:30.131 | ERROR    | __main__:<module>:8 - An error has been caught in function '<module>', process 'MainProcess' (50635), thread 'MainThread' (4445588928):
Traceback (most recent call last):
> File "/Users/mymac/.local/bin/roam-to-git", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x101774550>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/Users/mymac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/__main__.py", line 76, in main
    scrap(markdown_zip_path, json_zip_path, config)
    │     │                  │              └ <roam_to_git.scrapping.Config object at 0x10136b340>
    │     │                  └ PosixPath('/var/folders/gn/g76j1djs2jg435mw66t44gb00000gn/T/tmp9ydka31q')
    │     └ PosixPath('/var/folders/gn/g76j1djs2jg435mw66t44gb00000gn/T/tmpzms68d_n')
    └ <function scrap at 0x101774280>
  File "/Users/mymac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/scrapping.py", line 253, in scrap
    asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
    │       │                                   │       │       └ [<coroutine object download_rr_archive at 0x10175b2c0>, <coroutine object download_rr_archive at 0x10175b440>]
    │       │                                   │       └ <function gather at 0x10111d550>
    │       │                                   └ <module 'asyncio' from '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/_...
    │       └ <built-in function get_event_loop>
    └ <module 'asyncio' from '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/_...
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
           │      └ <method 'result' of '_asyncio.Future' objects>
           └ <_GatheringFuture finished exception=AssertionError('All roads leads to Roam, but that one is too long. Try again when Roam s...
  File "/Users/mymac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/scrapping.py", line 69, in download_rr_archive
    return await _download_rr_archive(document, output_type, output_directory, config)
                 │                    │         │            │                 └ <roam_to_git.scrapping.Config object at 0x10136b340>
                 │                    │         │            └ PosixPath('/var/folders/gn/g76j1djs2jg435mw66t44gb00000gn/T/tmpzms68d_n')
                 │                    │         └ 'markdown'
                 │                    └ <pyppeteer.page.Page object at 0x10281e8b0>
                 └ <function _download_rr_archive at 0x101774040>
  File "/Users/mymac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/scrapping.py", line 121, in _download_rr_archive
    assert dot_button is not None, "All roads leads to Roam, but that one is too long. Try " \
           └ None

**AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.**
Traceback (most recent call last):
  File "/Users/mymac/.local/bin/roam-to-git", line 8, in <module>
    sys.exit(main())
  File "/Users/mymac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/loguru/_logger.py", line 1149, in catch_wrapper
    return function(*args, **kwargs)
  File "/Users/my/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/__main__.py", line 76, in main
    scrap(markdown_zip_path, json_zip_path, config)
  File "/Users/mysmac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/scrapping.py", line 253, in scrap
    asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/mymac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/scrapping.py", line 69, in download_rr_archive
    return await _download_rr_archive(document, output_type, output_directory, config)
  File "/Users/mymac/.local/pipx/venvs/roam-to-git/lib/python3.9/site-packages/roam_to_git/scrapping.py", line 121, in _download_rr_archive
    assert dot_button is not None, "All roads leads to Roam, but that one is too long. Try " \
**AssertionError: All roads leads to Roam, but that one is too long. Try again when Roam servers are faster.**
2020-10-30 11:55:30.154 | DEBUG    | roam_to_git.scrapping:_kill_child_process:216 - Terminate child process [psutil.Process(pid=50641, name='Chromium', status='running', started='11:48:31'), psutil.Process(pid=50642, name='Chromium Helper', status='running', started='11:48:31'), psutil.Process(pid=50643, name='Chromium Helper', status='running', started='11:48:31')]

**Run `roam-to-git --debug notes/` and report what you get.**
It should open a Chrome front-end, an do the scrapping. The repository content will not be modified. If applicable, add screenshots to help explain your problem.

The job tries to enter Email and Password but - warning that email has bad format

![image](https://user-images.githubusercontent.com/59105136/97703748-0cb64880-1aa9-11eb-9c4b-a3d3b4590f63.png)

**Please complete the following information:**
- OS: [e.g. MacOs, Linux] MacOS
- Do you use Github Action? Yes
- Do you use multiple Roam databases? No
- Does roam-to-git use to work for you? When precisely did it stopped to work? First time trying
- Does some backup runs are still working? no

**Additional context**

**Comment by fernfialho** [comment]
I'm pretty much a beginner to using terminals to backup data in github. I appreciate you creating this solution Matthiew and thank you for looking into this issue. I found a link to the your repository in Roams Slack community. Thank you, Fernando

**Comment by MatthieuBizien** [comment]
The backup errors should be fixed by #92 🍾. 

I'm closing that issue, but feel free to re-open it if you get new errors.
