### ISSUE TITLE
Consistent failure: download_rr_archive - ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by Stvad** [MatthieuBizien/roam-to-git#9]
Starting this night it consistently fails with the following error:

```
Launch popup
Traceback (most recent call last):
  File "/Users/sitalov/.local/bin/roam-to-git", line 8, in <module>
    sys.exit(main())
  File "/Users/sitalov/.local/pipx/venvs/roam-to-git/lib/python3.8/site-packages/roam_to_git/__main__.py", line 68, in main
    scrap(markdown_zip_path, json_zip_path, config)
  File "/Users/sitalov/.local/pipx/venvs/roam-to-git/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 188, in scrap
    asyncio.get_event_loop().run_until_complete(asyncio.gather(*tasks))
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/sitalov/.local/pipx/venvs/roam-to-git/lib/python3.8/site-packages/roam_to_git/scrapping.py", line 95, in download_rr_archive
    export_all, = [b for b in divs_pb3 if await get_text(document, b) == 'export all']
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by MatthieuBizien** [comment]
Can you try with `--debug`?

**Comment by Stvad** [comment]
It seems to have started working properly after your recent commits :) Gonna close this for now
